{% set name = "quicksectx" %}
{% set version = "0.3.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/quicksectx-{{ version }}.tar.gz
  sha256: 2747d105c107de5458714750642b4e6a263206b3e1064d3957d6716b468d0c72

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
  host:
    - python
    - cython >=0.25,<3.0
    - pip
  run:
    - python
    - cython >=0.25,<3.0

test:
  imports:
    - quicksect
    - quicksectx
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jianlins/quicksectx
  summary: fast, simple interval intersection
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - skupr-anaconda
